In [51]:
import pandas as pd
import json

fileDir = 'C:/Users/m/Documents/GitHub/population-data-map-overlay/data/info_by_zipcode/'
fileName = 'ACS_14_5YR_S1901_with_ann.csv'
outFileName = 'test.json'

#optionally specify a var name to call this (for load in javascript)
yourVarName = 'zipIncomeVals'

#optionally specify a selection of column headers you want to keep
columnKeys = ['GEO.id2','HC01_EST_VC01','HC01_EST_VC02','HC01_EST_VC03','HC01_EST_VC04','HC01_EST_VC05','HC01_EST_VC06','HC01_EST_VC07','HC01_EST_VC08','HC01_EST_VC09','HC01_EST_VC10','HC01_EST_VC11','HC01_EST_VC13','HC01_EST_VC15','HC01_EST_VC18']


incomeByZipDf = pd.read_csv(fileDir+fileName,header=[0],skiprows=[1])
if columnKeys:
    incomeByZipDf = incomeByZipDf[columnKeys]

#generate a dictionary structure to map to json format
#use first column from input file (from columnKeys) as the key and everything else in another dictionary beneath that
#  where key=column_name, value=cell_val
jsonDict = {}
for rowIdx, rowData in incomeByZipDf.iterrows():
    zipId = rowData[columnKeys[0]]
    jsonDict[zipId] = dict(zip(columnKeys[1:],rowData[1:]))  #oh this is snazzy! it creates the dict under each zip in 1 line

#write to a json file. 
with open(fileDir+outFileName, 'w') as outFile:
    if yourVarName:
        outFile.write('var '+yourVarName+'=\n')
    json.dump(jsonDict, outFile)
    

headerDf = pd.read_csv(fileDir+fileName,header=[0],nrows=1)
if columnKeys:
    headerDf = headerDf[columnKeys]
headerDict = dict(zip(headerDf.columns[1:], headerDf.iloc[0].values[1:]))

with open(fileDir+'descriptions_'+outFileName, 'w') as describeOutFile:
    json.dump(headerDict, describeOutFile)

In [72]:
incomeByZipDf[columnKeys[2:]].describe()  #why is ity only giving me these 2 columns?!? I'm so confused

,HC01_EST_VC02,HC01_EST_VC03,HC01_EST_VC04,HC01_EST_VC05,HC01_EST_VC06,HC01_EST_VC07,HC01_EST_VC08,HC01_EST_VC09,HC01_EST_VC10,HC01_EST_VC11,HC01_EST_VC13,HC01_EST_VC15,HC01_EST_VC18
count,775,775,775,775,775,775,775,775,775,775,775,775,775
unique,133,130,178,172,180,198,186,221,111,94,730,759,242
top,0.0,0.0,0.0,10.9,14.4,22.1,14.9,0.0,0.0,0.0,-,-,23.9
freq,27,25,14,13,13,14,16,18,58,89,11,7,12

In [58]:
incomeByZipDf[incomeByZipDf['GEO.id2'] == 53593]

,GEO.id2,HC01_EST_VC01,HC01_EST_VC02,HC01_EST_VC03,HC01_EST_VC04,HC01_EST_VC05,HC01_EST_VC06,HC01_EST_VC07,HC01_EST_VC08,HC01_EST_VC09,HC01_EST_VC10,HC01_EST_VC11,HC01_EST_VC13,HC01_EST_VC15,HC01_EST_VC18
236,53593,8301,2.2,2.4,5.2,4.8,6.9,16.8,16.2,23.4,9.9,12.2,92869,113991,18.9

In [75]:
otherFile = fileDir+'descriptions.txt'
with open(otherFile, 'w') as describeTxtFile:
    describeTxtFile.write(str(headerDict))

In [ ]:
otherFile = fileDir+'descriptions2.txt'
with open(otherFile, 'w') as describeTxtFile:
    for key,val in headerDict.items():
        describeTxtFile.write('{}: {}'.format(key,val) )
    describeTxtFile.write(str(headerDict))